CREATE TABLE areaprotect (
  owner TEXT PRIMARY KEY,
  x1 INTEGER,
  y1 INTEGER,
  z1 INTEGER,
  x2 INTEGER,
  y2 INTEGER,
  z2 INTEGER,
  pvp TINYINTENGER(1),
  build TINYINTEGER(1),
  destroy TINYINTEGER(1)
);
